config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.valid?
      @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar-wagon">
      <%=  link_to image_tag("https://icon-icons.com/icons2/729/PNG/512/yelp_icon-icons.com_62753.png", width: 50, length: 50, border: 0), restaurants_path %>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.erb
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>
<%= render "form" %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <div class="restaurant">
    <div class="restaurant-name"><%= link_to restaurant.name, restaurant_path(restaurant) %></div>
    <%= restaurant.address %>
    - <%= link_to "Delete", restaurant_path(restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" }, id: "delete-index" %>
  </div>
<% end %>
<%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-primary" %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<%= render "form" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1> <h2><%= @restaurant.category.capitalize %></h2>
<button class="btn"><%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %></button>
<p>- Adress: <%= @restaurant.address %></p>
<p>- Phone number: <%= @restaurant.phone_number %></p>
<div class="reviews">
  <strong>Reviews:</strong>
  <% @restaurant.reviews.each do |review| %>
  <br>
    <% review.rating.times do %>
      <i class="fas fa-star"></i>
    <% end %>
    <% (5-(review.rating)).times do %>
      <i class="far fa-star"></i>
    <% end %>
    <%= review.content %>
  <% end %>
</div>
<div class="buttons">
  <%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  <%= link_to "Delete", restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" }, class: "btn btn-danger", id: "delete-index" %>
</div>
<%= link_to "Back to list", restaurants_path %>

app/views/reviews/_form.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :content %>
  <%= f.input :rating, :collection => %w[1 2 3 4 5] %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>New review for <%= @restaurant.name %></h1>
<%= render "form" %>
<div class="btn-cancel">
<%= link_to "Cancel", restaurant_path(@restaurant), class: "btn btn-danger" %>
</div>